name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "**/*.{astro,scss,js,css,ts,tsx,html}"
      - "public/**"
      - "astro.config.mjs"
      - ".github/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  R_BASE_URL: ${{ vars.R_BASE_URL }}
  R_HOSTNAME: ${{ vars.R_HOSTNAME }}

jobs:
  display-variables:
    name: Show build env vars
    if: ${{ vars.R_HOSTNAME != null }}
    runs-on: ubuntu-latest
    steps:
      - name: Use variables
        run: |
          echo "base url : $R_BASE_URL"
          echo "hostname : $R_HOSTNAME"
        env:
          R_BASE_URL: ${{ vars.R_BASE_URL }}
          R_HOSTNAME: ${{ vars.R_HOSTNAME }}

  build:
    needs: display-variables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site
        uses: withastro/action@v0
        with:
          node-version: 18
          package-manager: yarn

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
